### PR TITLE
Update simple card game

### PR DESCRIPTION
**Pull request by jayarudran**
python program to make simple card game

### CODE REVIEW

**Comment by jayarudran** [comment]
python program to make simple card game

**Comment by jayarudran** [comment]
python program to make simple card game

**Comment by fasalmbt** [comment]
@jayarudran this is not repository you mean. It's a repo for placement cell website. Closing this. Thank you

**Comment by codingclubcoet** [comment]
This is not the repository you think. This is a repo for placement cell website. Thank you.

**Pull request closed without merging**
